# Generated by Django 2.0.7 on 2018-09-28 18:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('rate_type', models.CharField(choices=[('H', 'Hour'), ('D', 'Day'), ('M', 'Month'), ('Y', 'Year')], max_length=1)),
                ('rate_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(message='Only letters are allowed', regex='^[a-zA-ZА-Яа-яІіЇїЄє]+$')])),
                ('name', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(message='Only letters are allowed', regex='^[a-zA-ZА-Яа-яІіЇїЄє]+$')])),
                ('middle_name', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(message='Only letters are allowed', regex='^[a-zA-ZА-Яа-яІіЇїЄє]+$')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Only digits and '+' are allowed in phone number", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('property_type', models.CharField(choices=[('Res', 'Residential'), ('Comm', 'Commercial')], max_length=4)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_app.Person')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_app.Property'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_app.Person'),
        ),
    ]
